### ISSUE TITLE
I'm shocked when reading the code: create 1 object with 6 "clone"

### ISSUE THREAD

**Issue by agussuhartono** [yiisoft/cookies#23]
I'm shocked when reading this code

$cookie = (new \Yiisoft\Cookies\Cookie('cookieName', 'value'))
    ->withPath('/')
    ->withDomain('yiiframework.com')
    ->withHttpOnly(true)
    ->withSecure(true)
    ->withSameSite(\Yiisoft\Cookies\Cookie::SAME_SITE_STRICT)
    ->withMaxAge(new \DateInterval('P7D'));
    
 this code, create 1 Cookie object with 6 object clone   
 
 every method with "with" prefix allways use clone to create object
 
 what is the purpose?

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/docs/issues/81.

@agussuhartono clone operation in PHP is **very cheap**. The purpose is to achieve object immutability. That prevents unwanted side effects leading to way too many bugs in applications.
