### ISSUE TITLE
Клонирование объекта

### ISSUE THREAD

**Issue by ohDaddyPlease** [yiisoft/cookies#3]
https://github.com/yiisoft/cookies/blob/bbbb27e610ec80d69259076f4400fd0237b83f6b/src/Cookie.php#L175

Не лучше ли вынести $new в свойство основного объекта?
Это даст возможность chain code вида:
`$cookie->new->withValue('test')->expire();`

**Comment by vjik** [comment]
> Не лучше ли вынести $new в свойство основного объекта?
> Это даст возможность chain code вида:
> `$cookie->new->withValue('test')->expire();`

Сейчас уже можно использовать так:
`$cookie->withValue('test')->expire();`

**Comment by ohDaddyPlease** [comment]
> > Не лучше ли вынести $new в свойство основного объекта?
> > Это даст возможность chain code вида:
> > `$cookie->new->withValue('test')->expire();`
> 
> Сейчас уже можно использовать так:
> `$cookie->withValue('test')->expire();`

Если взять методы [expire](https://github.com/yiisoft/cookies/blob/master/src/Cookie.php#L256), [withDomain](https://github.com/yiisoft/cookies/blob/master/src/Cookie.php#L282), то каждый вызов клонирует предыдущий объект (в случае код-чайна) и работает с ним. Если, к примеру, будет чайн из 10 методов, то, соответственно, будет вызвано 10 методов и склонировано 10 объектов.
Это не будет ли ресурсоёмко? Не лучше ли работать с одной копией объекта?

**Comment by romkatsu** [comment]
> > > Не лучше ли вынести $new в свойство основного объекта?
> > > Это даст возможность chain code вида:
> > > `$cookie->new->withValue('test')->expire();`
> > 
> > 
> > Сейчас уже можно использовать так:
> > `$cookie->withValue('test')->expire();`
> 
> Если взять методы, например, [expire](https://github.com/yiisoft/cookies/blob/master/src/Cookie.php#L256), [withDomain](https://github.com/yiisoft/cookies/blob/master/src/Cookie.php#L282), то каждый вызов клонирует предыдущий объект (в случае код-чайна) и работает с ним. Если, к примеру, будет чайн из 10 методов, то, соответственно, будет вызвано 10 методов и склонировано 10 объектов.
> Это не будет ли ресурсоёмко в некоторых случаях? Не лучше ли работать с одной копией объекта, а не плодить при каждом вызове?

Реуресурсоёмко - думаю нет. 

Это делается чтобы избежать скрытого поведения объекта:

```php
class Foo {
     private $value;

     function setValue($arg) {
        $this->value = $arg;
        return $this;
     }

     function printValue() {
         echo $this->value.PHP_EOL;
     }
}


$a = (new Foo)->setValue('a');
$b = $a->setValue('b');

$a->printValue();
$b->printValue();
```

Получим:
```
b
b
```

Если заменить реализацию на:
```php
     function setValue($arg) {
        $clone = $this;
        $clone->value = $arg;
        return $clone;
     }
```

Получим:
```
a
b
```

Такие ошибки тяжело "ловить" по этому рекомендуется использовать клонирование или void сеттеры.

**Comment by ohDaddyPlease** [comment]
Но если мы возьмем такой пример:
`...
$otherCookie = $cookie->withDomain('dom');
if ( ... ) {$otherCookie = $otherCookie->withValue('val'); } 
  else { $otherCookie  = $otherCookie->withValue('val2''); }
...
работаем с $otherCookie
`
Из-за того, что каждый вызов подобных методов возвращает копию объекта, то придётся каждый раз присваивать или новой, или старой переменной новый объект. Это из код-стайла очень странное решение получится.
Также, подобный подход в других компонентах используется, поэтому это общая проблема без затрагивания конкретно компонентных особенностей.

**Comment by samdark** [comment]
@ohDaddyPlease клонирование не дорогое, immutability того стоит.
